version: '3'
services:
  datdashboard:
    image: $DOCKER_IMAGE:$DOCKER_TAG
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
